pingdotgg/uploadthing

docs/src/theme.config.js

fix: update broken discord link

---

turbo.json

any reason you were ignoring this?

don't ignore cache output

---

docs/src/pages/nextjs/pagedir.mdx

fixed import bug in docs

---

docs/src/pages/create-account.mdx
docs/src/pages/index.mdx

I went ahead and added a few links to make it easier to navigate to the main site while using the docs.

Links added to main site to make docs slightly easier to use

---

docs/src/pages/nextjs/_meta.json
docs/src/pages/nextjs/appdir.mdx
docs/src/pages/nextjs/pagedir.mdx

https://clips.twitch.tv/HappyVictoriousBobaWOOP-SCQJW_mvwwQFwcWg

Docs edit: `app/`, not `/app`

---

docs/src/pages/nextjs/pagedir.mdx

Add style import to pagedir example

[docs] Add style import to pagedir example

---

docs/src/pages/nextjs/appdir.mdx
docs/src/pages/nextjs/pagedir.mdx
examples/appdir/src/app/page.tsx
examples/pagedir/src/pages/index.tsx
examples/pagedir/src/styles/globals.css
packages/react/src/component.tsx
packages/react/src/useUploadThing.ts
packages/uploadthing/client.ts
packages/uploadthing/src/internal/handler.ts

- better errrors from the client
- catch errror in hook
- add onUploadError to components
- update examples
- update docs

[UPL-37] Better Error Flow

---

docs/src/theme.config.js

Docs: Added Dark Mode

---

.changeset/rotten-numbers-tan.md
packages/uploadthing/src/internal/handler.ts

- Added input validation using a regular expression to ensure the `size` parameter is in the correct format.
- Modified the function to return an `Error` object when encountering invalid size formats or units, allowing for graceful error handling.
- Extracted the conversion factors into a separate `conversionFactors` object for improved readability and maintainability.
- Updated variable naming for clarity and consistency.
- Allowed for decimal numbers in the file size and implemented case-insensitive unit matching.
- cast back to int in the return (Thanks @markflorkowski )

file size improvements

---

docs/package.json
examples/appdir/package.json
examples/pagedir/package.json
package.json
packages/react/package.json
packages/uploadthing/package.json
pnpm-lock.yaml
turbo.json

fixes issue where pnpm dev fails on first run

---

.eslintrc.cjs
common/eslint-config-custom/index.js
common/eslint-config-custom/package.json
docs/next.config.mjs
examples/appdir/.eslintrc.js
examples/appdir/next.config.js
examples/appdir/src/app/_uploadthing/index.ts
examples/pagedir/.eslintrc.js
examples/pagedir/next.config.js
examples/pagedir/src/server/uploadthing/router.ts
packages/react/tsconfig.json
packages/uploadthing/client.ts
packages/uploadthing/src/next/core/approuter.ts
packages/uploadthing/src/next/core/page.ts
packages/uploadthing/src/upload-builder.ts
packages/uploadthing/tsconfig.json
pnpm-lock.yaml

closes #26 
might want to look into fixing some of the `any`'s. For now i just disabled them on a per-page basis

enable stricter lint + tame the linter

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/code-of-conduct.md

ADDED issue template for bug report

---

docs/src/pages/index.mdx
docs/src/pages/solid.mdx

feat(docs): tabs for all package managers

---

.changeset/pink-forks-bake.md
packages/uploadthing/src/types.ts

Now includes `size` parameter to reflect change to infra

[types] Update types for onUploadComplete

---

docs/src/pages/index.mdx
docs/src/pages/solid.mdx

prettier messed up the code tags and made it look like this:

fix package manager tabs

---

docs/src/pages/index.mdx
package.json
packages/uploadthing/package.json
packages/uploadthing/src/constants.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/types.ts
packages/uploadthing/src/next/core/approuter.ts
packages/uploadthing/src/next/core/page.ts
packages/uploadthing/src/types.ts
pnpm-lock.yaml

Closes #83 and also performs some general hoursekeeping to silence some lint rules

chore: housekeeping 1 - fix lint stuff

---

.changeset/ninety-monkeys-notice.md
packages/uploadthing/server.ts
packages/uploadthing/src/helper-functions.ts
packages/uploadthing/src/internal/handler.ts

- Adds an export from `uploadthing/server` for `utapi`
- `deleteFiles()` function -- takes an array of file keys to 
be deleted, and makes request to delete files
- `getFileUrls()` function -- takes an array of file keys to 
retrieve their urls

[feat] UTAPI Helpers

---

docs/src/pages/_meta.json
docs/src/pages/api-reference/_meta.json
docs/src/pages/api-reference/react.mdx
docs/src/pages/api-reference/server.mdx

I plan to update the examples with default values and such after the v4 changes merge. Same w/ the TODO. Just don't want things out of sync with the repo as much as possible

[docs] api reference docs

---

packages/uploadthing/src/next/core/page.ts

pages dir is not working now, it needs to be parsed.
I hope this commit be helpful

fix: page dir's req body needs to be parsed

---

.changeset/shaggy-trees-sort.md
package.json
packages/uploadthing/client.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/types.ts
packages/uploadthing/src/utils.ts
pnpm-lock.yaml

Adds PDF and Text file support for uploaders
Note: Requires changes on infra side to be merged 
first

[feat] Additional file types 

---

.changeset/hungry-horses-think.md
packages/react/src/useUploadThing.ts

🤷🏼
Closes #130 (although I couldn't repro it on React ^18 which it looked like OP was on, this fixes the issue all the way down to React 17)

fix: add back support for react 17

---

.changeset/chatty-plants-allow.md
packages/uploadthing/src/internal/handler.ts

It was inverted from what it should have been.
closes #144

[fix] Correct logic for dev server running message

---

.changeset/quiet-cheetahs-drop.md
packages/react/src/useUploadThing.ts
packages/uploadthing/client.ts

Reverting changes from #122 due to issues with CORS

[fix] don't prefetch component data on server

---

.changeset/little-berries-wash.md
packages/react/src/component.tsx

Since we are not prefetching component data on server, we need a better loading state. Also works on pages dir. 
https://github.com/pingdotgg/uploadthing/assets/11494384/50704dfe-b914-4196-b4c5-fb1caa2b0589

[misc] Better component loading state

---

docs/src/pages/api-reference/server.mdx

[docs] Fix file size in example

---

packages/react/src/client-generator.test.ts
packages/react/src/useUploadThing.ts

hi julius
I changed the input signature when making this work and didn't try changing it back. I think endpoint being separate from config is preferable tho

fix remaining tests in upload-params

---

.changeset/empty-jokes-type.md
.changeset/pink-kids-shop.md
packages/solid/package.json

fix: changeset

---

examples/appdir/package.json
examples/appdir/src/app/image-crop/image-cropper.tsx
examples/appdir/src/app/image-crop/page.tsx
package.json
pnpm-lock.yaml

We don't have any example of usage with the hook. I thought this could be useful 🤷🏼 
https://github.com/pingdotgg/uploadthing/assets/51714798/47e0cca5-9ea9-4662-9ea8-5f60b0535af5

showcase: show usage for cropping before uploading

---

.github/workflows/pr-titles.yaml

This should make it easier to automate changelogs, and provide more 
consistent versioning

chore(actions): Validate PR titles follow conventional commits format

---

.changeset/ten-plums-notice.md
docs/src/pages/errors.mdx
examples/appdir/src/app/api/uploadthing/route.ts
examples/appdir/src/app/sink/page.tsx
examples/appdir/src/server/uploadthing.ts
package.json
packages/react/src/component.tsx
packages/react/src/useUploadThing.ts
packages/shared/src/error.ts
packages/shared/src/index.ts
packages/shared/src/types.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/error-formatter.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/next/approuter.ts
packages/uploadthing/src/internal/next/pagerouter.ts
packages/uploadthing/src/internal/parser.ts
packages/uploadthing/src/internal/types.ts
packages/uploadthing/src/internal/upload-builder.ts
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/src/next.ts
packages/uploadthing/src/server.ts

Closes UPL-54
Closes #198
Might be related to #189

feat: errorFormatter

---

.changeset/friendly-mayflies-promise.md
packages/uploadthing/src/internal/handler.ts

fixes https://discord.com/channels/966627436387266600/1102510616326967306/1130116966162645073

fix: pagedir not using absolute url

---

.changeset/pink-sloths-tan.md
docs/src/pages/api-reference/server.mdx
examples/appdir/src/app/server/page.tsx
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/utils.ts

feat: upload from url

---

docs/src/pages/api-reference/react.mdx
docs/src/pages/api-reference/server.mdx
docs/src/pages/errors.mdx

Resolves https://discord.com/channels/@me/1068689799134851163/1132938040340385792

docs: version notes

---

docs/src/pages/errors.mdx

Fixed minor issue with the name of the error handler property on the premade components.

fix: Update errors.mdx minor typo

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml

hate when people don't provide a repro

fix: require repro to open an issue

---

.changeset/twenty-trains-study.md
examples/appdir/src/server/uploadthing.ts
packages/react/src/useUploadThing.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/types.ts
packages/uploadthing/src/internal/upload-builder.ts
packages/uploadthing/src/sdk/utils.ts

Reverts pingdotgg/uploadthing#189

Revert "feat: Handle failed uploads (UPL-60)"

---

.changeset/twenty-trains-study.md
examples/appdir/src/server/uploadthing.ts
packages/react/src/useUploadThing.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/types.ts
packages/uploadthing/src/internal/upload-builder.ts
packages/uploadthing/src/sdk/utils.ts

Reverts pingdotgg/uploadthing#300

feat: Handle failed uploads (UPL-60) 

---

examples/minimal-appdir/package.json
examples/minimal-pagedir/package.json
examples/with-react-image-crop/package.json
examples/with-tailwindcss/package.json
pnpm-lock.yaml

fix(examples): add missing deps

---

docs/src/pages/api-reference/react.mdx

Example referenced functions that were not imported/did not exist

fix(docs): Example usage of useUploadThing

---

.changeset/config.json
examples/minimal-appdir/package.json
examples/minimal-pagedir/package.json
examples/minimal-solidstart/package.json
examples/with-clerk-appdir/package.json
examples/with-drizzle-appdir/package.json
examples/with-react-image-crop/package.json
examples/with-serveractions/package.json
examples/with-tailwindcss/package.json

fix: ignore glob pattern for examples

---

.changeset/smooth-hornets-call.md
packages/uploadthing/src/internal/handler.ts

Ref: https://discord.com/channels/966627436387266600/1102510616326967306/1152679262336339968

fix: move log to prevent spam in dev

---

packages/react/src/components/button.tsx

Addresses #391
To Do:
- Add focus ring

fix(components): Allow upload button to be focusable via keyboard

---

.changeset/seven-avocados-tie.md

chore:  Add missing changeset

---

.changeset/seven-avocados-tie.md
packages/react/src/components/button.tsx

Accidentally chose wrong base.

fix: Actually merge missing changeset

---

packages/uploadthing/src/internal/incompat-node-guard.ts

fix: incompat node guard for node > 18

---

.changeset/grumpy-beds-check.md
packages/uploadthing/src/sdk/utils.ts

fix: checking wrong env for sdk api key check

---

.github/workflows/ci.yaml
.github/workflows/examples.yaml
.gitignore
docs/next-env.d.ts
examples/minimal-appdir/next-env.d.ts
examples/minimal-pagedir/next-env.d.ts
examples/with-clerk-appdir/next-env.d.ts
examples/with-clerk-pagesdir/next-env.d.ts
examples/with-drizzle-appdir/next-env.d.ts
examples/with-drizzle-pagesdir/next-env.d.ts
examples/with-react-image-crop/next-env.d.ts
examples/with-serveractions/next-env.d.ts
examples/with-tailwindcss/next-env.d.ts
tooling/gh-actions/setup/action.yml
turbo.json

use more runners to avoid hitting turbo concurrency limit

chore: faster CI

---

docs/src/pages/_meta.json
docs/src/pages/getting-started/_meta.json
docs/src/pages/getting-started/_shared/env-setup.mdx
docs/src/pages/getting-started/appdir.mdx
docs/src/pages/getting-started/astro.mdx
docs/src/pages/getting-started/nuxt.mdx
docs/src/pages/getting-started/pagedir.mdx
docs/src/pages/getting-started/solid.mdx
docs/src/pages/getting-started/svelte.mdx
docs/src/pages/nextjs/_meta.json
docs/src/theme.config.js

- Reorganized docs structure
- Added "coming soon" to upcoming frameworks
- Moved Getting Started to shared component between setup guides
- Small theming things

docs: Docs overhaul

---

docs/src/pages/backend-adapters/express.mdx
docs/src/pages/backend-adapters/fastify.mdx
docs/src/pages/backend-adapters/fetch.mdx
docs/src/pages/backend-adapters/h3.mdx

in the future we might also wanna create redirects when changing links so that the old ones continue to work

docs: fix broken links

---

docs/src/pages/api-reference/react.mdx

docs: Fix a typo in react api reference

---

.changeset/thirty-masks-fetch.md

previous one got a bit messed up and we changeset the wrong thing 😅

chore: changeset for mime-types

---

.changeset/famous-hornets-matter.md
packages/shared/src/types.ts
packages/shared/src/utils.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/dev-hook.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/multi-part.ts
packages/uploadthing/src/internal/types.ts
packages/uploadthing/src/internal/ut-reporter.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/utils.ts

Needs https://app.graphite.dev/github/pr/pingdotgg/uploadthing-infra/219/feat-multi-part-uploads

feat!: multipart uploads

---

.vscode/operators.code-snippets
packages/shared/package.json
packages/shared/src/error.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/effect-utils.ts
packages/uploadthing/src/internal/ut-reporter.ts
pnpm-lock.yaml

chore(effect refactoring): remove Effect.die + improve UploadThingError

---

.changeset/young-trains-smoke.md
packages/uploadthing/tsup.config.ts

fix: make Express external dependency

---

packages/uploadthing/tsup.config.ts

Follows up #479
Some comparisons, see old output here: https://www.npmjs.com/package/uploadthing/v/6.0.1?activeTab=code

chore: more externals

---

.changeset/curly-lions-enjoy.md
packages/react/src/components/button.tsx
packages/shared/src/utils.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/express.ts
packages/uploadthing/src/fastify.ts
packages/uploadthing/src/h3.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/src/server.ts

Closes #474
Closes #475 
Using SSE causes some race conditions we don't wanna deal with and sometimes causes the polling request to time out. Using a callback instead as discussed

fix: don't use sse

---

.changeset/silver-peas-behave.md
packages/shared/src/utils.ts
packages/uploadthing/src/internal/dev-hook.ts

fix: return a random Symbol from dev hook to stop exponential backoff

---

docs/src/pages/api-reference/react.mdx

docs: update uploadFiles to v6 API

---

.changeset/fair-beans-sin.md
packages/uploadthing/src/internal/handler.ts

this should handle almost everything i hope 😅

fix: url parsing from headers if req.url is localhost

---

docs/src/pages/faq.mdx
docs/src/pages/theming.mdx

I closed the previous pull request and made a new branch.
Fixed typo errors in the documentation. Corrected spelling mistakes.

docs: Fixed 22 typo errors in the documentation 

---

.changeset/forty-walls-applaud.md
packages/shared/src/utils.ts

https://discord.com/channels/966627436387266600/1102510616326967306/1187504114242961541
also need to update infra to use this new version of `@uploadthing/shared` once released

fix: fallback to blob type when determining mime-type

---

docs/src/pages/getting-started/appdir.mdx

closes issue [532](https://github.com/pingdotgg/uploadthing/issues/532)

docs(appdir): emphasize useclient with UploadButton

---

.changeset/neat-geckos-sell.md
packages/uploadthing/src/sdk/index.ts

chore: pluralize-renamefiles

---

.changeset/curly-schools-decide.md
packages/react/src/types.ts

feat: allow async on onBeforeUploadBegin on provided components

---

docs/src/pages/faq.mdx

docs: Add a note to FAQ about edge runtime errors in dev

---

docs/src/pages/api-reference/react.mdx
docs/src/pages/faq.mdx
docs/src/pages/getting-started/appdir.mdx
docs/src/pages/getting-started/pagedir.mdx
docs/src/pages/getting-started/solid.mdx

chore(docs): Update docs to use new split component generators

---

.changeset/dry-bobcats-shop.md
packages/react/src/useUploadThing.ts
packages/solid/src/useUploadThing.ts

fix: omit `pacakge` from uploadFiles type

---

docs/src/pages/getting-started/appdir.mdx
docs/src/pages/getting-started/pagedir.mdx

docs: update usage of `UploadThingError`

---

docs/src/pages/faq.mdx

maybe wait for an actual release, idk

docs: edge note

---

docs/src/pages/backend-adapters/express.mdx
docs/src/pages/backend-adapters/fastify.mdx
docs/src/pages/backend-adapters/fetch.mdx
docs/src/pages/backend-adapters/h3.mdx

docs: add note about url

---

.changeset/smart-bugs-train.md
packages/react/src/next-ssr-plugin.tsx

Closes #608 
https://github.com/pingdotgg/uploadthing/assets/51714798/36bf6dd5-de9f-4baf-b507-d9ec1fe7a12d

fix: always reassign everytime plugin re-renders

---

packages/uploadthing/src/constants.ts

got lucky it lined up this time :)

fix: revert version override

---

.changeset/early-lobsters-matter.md
packages/uploadthing/src/express.ts
packages/uploadthing/src/fastify.ts
packages/uploadthing/src/internal/node-http/toWebRequest.ts
packages/uploadthing/src/next-legacy.ts

Ref: https://discord.com/channels/966627436387266600/1205382848971014144/1205419258478338088

fix: try different stuff when parsing relative URL from `NodeJS.IncomingMessage`

---

.changeset/old-moles-jump.md
packages/uploadthing/src/internal/dev-hook.ts

should hopefully reduce the amount of questions we get from this error

chore: expand error logged when callback fails

---

.changeset/popular-eels-talk.md
docs/src/pages/api-reference/ut-api.mdx
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/test/sdk.test.ts

feat: allow setting customid from uploadFilesFromUrl

---

.changeset/giant-penguins-hang.md
packages/shared/src/types.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/constants.ts
packages/uploadthing/src/express.ts
packages/uploadthing/src/fastify.ts
packages/uploadthing/src/h3.ts
packages/uploadthing/src/internal/constants.ts
packages/uploadthing/src/internal/dev-hook.ts
packages/uploadthing/src/internal/get-full-url.test.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/ut-reporter.ts
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/types.ts
packages/uploadthing/src/sdk/utils.ts
packages/uploadthing/src/server.ts
packages/uploadthing/test/__test-helpers.ts
packages/uploadthing/test/sdk.test.ts

chore: move some stuff

---

.changeset/neat-feet-breathe.md
.changeset/sweet-zebras-live.md
packages/react/package.json
packages/react/src/components/button.tsx
packages/react/src/components/dropzone.tsx
pnpm-lock.yaml

https://github.com/pingdotgg/uploadthing/assets/51714798/867ccbc8-ab50-4b98-8ef5-c952b14cd939
https://github.com/pingdotgg/uploadthing/assets/51714798/a7ff8c96-2e87-4414-8b8a-85279e7793de

feat(react): add progress bar to dropzone, fix progress percentage `z-index`

---

.changeset/quiet-fireants-agree.md
packages/dropzone/package.json
packages/dropzone/src/core.ts
pnpm-lock.yaml

4 year old code with shit esm support, might as well bundle it so we don't need that nasty hack to get it sort of working in some environments...

chore: bundle attr-accepts

---

.changeset/sweet-parents-greet.md
packages/mime-types/src/db.ts

https://www.digipres.org/formats/mime-types/#audio/x-gsm

feat: Add audio/x-gsm to mime-types db.ts

---

.changeset/sweet-parents-greet.md

fix: adjust changeset

---

docs/src/pages/getting-started/appdir.mdx
docs/src/pages/getting-started/pagedir.mdx

Trying to get upload% under 40s 👀

docs: comment out config by default

---

.changeset/metal-zoos-argue.md
packages/uploadthing/src/internal/types.ts

fix: CustomId should be optional in middleware

---

docs/src/components/scalar.tsx
docs/src/globals.css
docs/src/pages/api-reference/_meta.json

chore(docs): Remove unnecessary effect from OpenAPI doc page

---

.changeset/yellow-cats-report.md
packages/uploadthing/src/tw.ts

Closes https://github.com/pingdotgg/uploadthing/issues/719

fix: platform agnostic pathing for twPlugin

---

packages/dropzone/src/solid.tsx

Not sure why this wasn't caught in other branches, but should resolve lint issue for https://github.com/pingdotgg/uploadthing/pull/225#issuecomment-2019130693

chore: solid pass @typescript-eslint/prefer-optional-chain

---

.changeset/ninety-chicken-know.md
docs/src/pages/api-reference/server.mdx
packages/shared/src/component-utils.ts
packages/shared/src/types.ts
packages/shared/src/utils.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/test/adapters.test.ts
packages/uploadthing/test/request-handler.test.ts
packages/uploadthing/test/upload-builder.test.ts

Addresses #710
- **add minFileCount option to RouteConfig**
- **update docs to include minFileCount**
To do:

feat: minFileCount option on RouteConfig

---

.vscode/settings.json
docs/tailwind.config.ts

fix(docs): Force styles to be included in docs site build 

---

.changeset/small-squids-drive.md
packages/mime-types/src/db.ts

ref: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types

chore: update jpeg file extensions

---

.changeset/happy-numbers-bow.md
packages/shared/src/effect.ts
packages/uploadthing/src/client.ts

this goes deep, so 1 small change at a time, ya know?

refactor(client): move things to pipelines

---

docs/src/pages/api-reference/react.mdx

docs: fix typo on react api reference

---

.changeset/lovely-hounds-cross.md
.changeset/sharp-dogs-bow.md
packages/shared/package.json
packages/shared/src/component-utils.ts
packages/shared/src/effect.ts
packages/shared/test/component-utils.test.ts
packages/uploadthing/src/internal/logger.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/utils.ts
packages/uploadthing/test/sdk.test.ts
pnpm-lock.yaml
tooling/gh-actions/setup/action.yml
vitest.config.ts

fix: better mime type support for generic types

---

.changeset/fuzzy-toys-smell.md
.vscode/settings.json
examples/minimal-sveltekit/src/routes/+page.svelte
packages/solid/src/components/dropzone.tsx
packages/svelte/src/lib/component/UploadDropzone.svelte
packages/vue/src/components/dropzone.tsx

feat: add onDrop to remaining libs

---

.github/workflows/examples.yaml
examples/backend-adapters/package.json
examples/backend-adapters/playwright.config.ts
examples/backend-adapters/test/smoke.test.ts
package.json
pnpm-lock.yaml
turbo.json

#823 reminded me that we have one of these setup - might as well run it in CI?

test: fix e2e test and add to matrix

---

.changeset/tiny-rocks-yawn.md
docs/src/pages/api-reference/react.mdx
docs/src/pages/api-reference/server.mdx
packages/react/src/components/button.tsx
packages/react/src/components/dropzone.tsx

Addresses https://discord.com/channels/966627436387266600/1243708607346769951/1243708607346769951

feat: Ability to set `disabled` prop on components

---

packages/uploadthing/test/__test-helpers.ts
packages/uploadthing/test/client.test.ts

while debugging #841 Tim and I discovered the tests were a bit flaky.
this brings the fixes we incorporated over there as it's own PR

fix: test flakiness

---

.github/analyze-bundle.js
.github/workflows/ci.yaml
package.json
pnpm-lock.yaml

With the introduction of `effect/Micro` it'd be useful to know when the client bundle size changes

chore: add bundle analysis to CI

---

.changeset/breezy-geckos-smoke.md
examples/backend-adapters/server/package.json
packages/shared/package.json
packages/uploadthing/package.json
pnpm-lock.yaml

chore: bump effect versions

---

.changeset/quiet-drinks-glow.md
examples/backend-adapters/server/package.json
examples/backend-adapters/server/tsconfig.json
examples/backend-adapters/server/wrangler.toml
packages/shared/package.json
packages/uploadthing/package.json
pnpm-lock.yaml

follow-up #871
fixes upstream issue with cf workers: https://github.com/Effect-TS/effect/issues/3057

chore: bump effect

---

flake.nix

I noticed some minor changes to improve the flake.nix file:
- inlining `pkgs` declaration within the `forAllSystems`
- replacing `runCommand` with `WriteShellScriptBin`
- using flake exposed systems list (4 -> 11 supported systems)

refactor: Improve flake

---

LICENSE

https://youtu.be/IhnN_qKwDus?si=nBm2Qd0R3hrhr5Dl&t=188

docs: update year in license

---

.changeset/popular-zoos-sin.md
packages/uploadthing/src/sdk/types.ts
packages/uploadthing/test/sdk.test.ts

https://discord.com/channels/966627436387266600/1102510616326967306/1276220926870028421

fix: types for renameFiles match infra

---

.changeset/slimy-pets-march.md
packages/shared/src/crypto.ts

https://discord.com/channels/966627436387266600/1102510616326967306/1277382928388722819

fix: remove Node.js Buffer reference

---

examples/with-novel/package.json
package.json
pnpm-lock.yaml
tooling/eslint-config/package.json

https://thingsbyping.slack.com/archives/C052S77L05C/p1724966211305329

chore: bump turbo

---

docs/next-sitemap.config.js
docs/package.json
docs/src/pages/getting-started/nuxt.mdx
docs/src/theme.config.js
package.json
pnpm-lock.yaml

chore: deprecate old docs

---

.changeset/flat-seals-change.md
packages/svelte/package.json

chore: update svelte peer dep range
