pingdotgg/uploadthing

packages/uploadthing/src/internal/handler.ts

When UploadThing's webhook makes a request to the callback URL, the request handler does not `await` the user supplied callback function. It is expected that users will supply an async callback to persist state in their database or otherwise process the new file, and therefore it is appropriate to `await` it.
This does not cause any issues in dev mode, but when hosting on Vercel in production it will cause the callback function to be prematurely terminated (probably at the first time it yields?), causing buggy behavior.

Use await when invoking callback

---

packages/uploadthing/package.json

Currently the `server` export is missing the `node` export for Node.js
I needed to patch this to add support in my websocket server which was running on Node.js

feat: node.js export

---

.changeset/olive-doors-kick.md
packages/react/src/component.tsx

This will allow multiple files to be passed when using the uploadButton comp (let the user select more than 1 file optionally)
this also fixes the mimeTypes for uploadButton (it was joined with "," when it should have been ", " therefore it didn't work and you could pass any file you want)
closes https://github.com/pingdotgg/uploadthing/issues/37

fix(uploadButton): accept mimeTypes join & allow multiple files to pass

---

docs/src/theme.config.js

Add a GitHub icon button in top right that links to this repo. Using Nextra theme config.

docs: add github link

---

.changeset/swift-bottles-dream.md
packages/uploadthing/src/internal/handler.ts

- Updated `buildRequestHandler` 
- Now uses `config.uploadthingSecret` instead of `config.uploadthingId`
- Throws an error if secret does not exist
- Renamed `upSecret` to `preferredOrEnvSecret`

[Fix] Update to buildRequestHandler secret

---

packages/uploadthing/src/types.ts
packages/uploadthing/src/upload-builder.test.ts
packages/uploadthing/src/upload-builder.ts

Use a single function instead of interpreting from multiple signatures and use arguments from the `Args` type so it's still customizable.
It's also possible to use the code below, but it would give an error to the user if they wrote this `.middleware((req) => {...})` so they would need to write `.middleware((req, _res) => {...})` if they didn't need the response when using `next-legacy`.
```typescript
type MiddlewareFn<
TOutput extends Record<string, unknown>,
TRuntime extends string
> = Args<TRuntime>["res"] extends never
? (req: Args<TRuntime>["req"]) => MaybePromise<TOutput>
: (
req: Args<TRuntime>["req"],
res: Args<TRuntime>["res"]
) => MaybePromise<TOutput>;
```
But the one plus would be it doesn't allow the `.middleware((req, _res) => {...})` when using `next` or `server`, while in …

Removed @ts-expect-error for middleware in upload-builder.ts

---

docs/src/pages/api-reference/react.mdx

Closes #114
These should be imported from the `/hooks` entrypoint:

fix(docs): update import for hooks

---

docs/src/pages/nextjs/pagedir.mdx

The server code snippet for the Next.js page dir docs is missing type imports

[docs] added missing type import in next.js page dir server snippet

---

.changeset/few-snakes-itch.md
packages/react/src/component.tsx

Fixes #140
Clears `files` state onUploadComplete for react-dropzone

fix(react-UploadDropzone): clear files onClientUploadComplete

---

.changeset/honest-seas-rush.md
docs/src/pages/nextjs/appdir.mdx
docs/src/pages/nextjs/pagedir.mdx
docs/src/pages/solid.mdx
examples/appdir/src/app/page.tsx
examples/appdir/src/utils/uploadthing.ts
examples/pagedir/src/pages/index.tsx
examples/pagedir/src/utils/uploadthing.ts
examples/solid/src/routes/index.tsx
examples/solid/src/utils/uploadthing.ts
packages/react/index.ts
packages/react/src/component.tsx
packages/solid/src/component.tsx

Instead of having to pass the generic everytime, you can now create type safed  components using the `generateReactComponents` method.
```ts
import { generateComponents } from "@uploadthing/react";
import type { OurFileRouter } from "~/server/uploadthing";
export const { UploadButton, UploadDropzone, Uploader } =
generateComponents<OurFileRouter>();
```
This can later be used like:
```tsx
<UploadButton
endpoint="withoutMdwr"
onClientUploadComplete={(res) => {
// Do something with the response
console.log("Files: ", res);
alert("Upload Completed");
}}
onUploadError={(error: Error) => {
alert(`ERROR! ${error.message}`);
}}
/>
```

feat: generateComponents function for React & Solid

---

docs/src/pages/nextjs/appdir.mdx

[According to /app dir docs ](https://docs.uploadthing.com/nextjs/appdir#creating-your-first-fileroute) we should create the router and export the type at app/api/uploadthing/core.ts.
[Later, it mentions that the type should be imported from server/uploadthing.ts](https://docs.uploadthing.com/nextjs/appdir#creating-the-uploadthing-components-optional)

Fix nonexistent location in docs

---

.changeset/long-cameras-change.md
examples/appdir/src/utils/uploadthing.ts
packages/shared/src/types.ts

Seems to be a typescript bug, where typescript is either getting confused, or doing some sort of optimization too agressivly. I highly recomend double checking to make sure this works for others as well.

fix(types): bizzare typescript bug

---

docs/src/pages/solid.mdx

Not super familiar with SolidStart but as-is this gives a type error.

docs: destructure `req` in middleware

---

.changeset/config.json
.changeset/metal-parents-bow.md

should fix the failing workflow
will force a release of the react and solid pacakges needed in order to fix the declaration bug that the current changeset indicates
alternatively we can change the current changeset to manually bump these packages if we don't want them to always be locked to one another

fix(changeset): add changeset for react and solid packages

---

.changeset/quick-carpets-refuse.md
packages/shared/src/utils.ts

We should default to the `UPLOADTHING_URL` if it is set, always.

fix(shared): Swap order of cases in getUploadthingUrl()

---

.changeset/curvy-crabs-teach.md
packages/uploadthing/src/client.ts

Closes #212
The issue is that `generateMimeTypes` function always append `*` to the type
It leads to error when using, for instance, `audio/mpeg` being turned into `audio/mpeg/*` which is invalid mime type
I added check for `/` in original type to differentiate precise MIME types from generic ones like `video`, `image`, `audio`

fix: improper MIME type mapping of precise MIME types

---

.changeset/spicy-candles-agree.md
docs/src/pages/_meta.json
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/next/approuter.ts

Regression of the `errorFormatter`. The middleware function can throw and will cause the entire API function to throw since we're now relying on the `requestHandler` to return the error instead of throwing it. I wish there was a way for TypeScript to know if your function can throw or not and show it on the type level :/
Closes #218

fix: wrap execution of middleware in try-catch

---

.changeset/large-nails-boil.md
packages/uploadthing/src/sdk/index.ts

Some are confused when getting the `"Missing UPLOADTHING_SECRET env variable."` error message when they try to use the utapi on the client. This improves that by adding a server only guard

chore: add server only guard

---

.changeset/little-dogs-exercise.md
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/sdk.test.ts
packages/uploadthing/src/sdk/utils.ts

I suck at Git so I have now made 3 PRs just cause i couldn't push to the orignial branch in #243 🤣 
(This is still not typesafe (due to the the `as` cast) but it's a bit tidier than it was before and I added some internal checks to the `uploadFilesInternal` to ensure that returns the correct shape)
Closes #243

fix: `uploadFiles` wrong runtime return type

---

.changeset/tender-bags-complain.md

add missing changeset from server upload PR.
need the `UploadthingError.toObject` method to be published

chore: add missing changeset from server upload PR.

---

.changeset/violet-pumas-talk.md
examples/appdir/src/app/page.tsx
packages/react/src/component.tsx
packages/react/src/useUploadThing.ts
packages/solid/src/component.tsx
packages/solid/src/useUploadThing.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/sdk/utils.ts

Addresses https://discord.com/channels/966627436387266600/1102510616326967306/1138143461908951111
Previously was only providing file key and url, now includes name and size as well 
to match with the input to `onUploadComplete()`
would be nice to have the objects be identical, however that would break back 
compat. 
`onUploadComplete()` uses this shape:
```
{
url: string,
key: string,
name: string, 
size: number
}
```
while `onClientUploadComplete()` uses:
```
{
fileName: string,
fileSize: number,
fileKey: string,
fileUrl: string
}
```

fix: pass same info to onClientUploadComplete as onUploadComplete

---

.changeset/real-bulldogs-protect.md
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/next/pagerouter.ts
packages/uploadthing/src/internal/types.ts

Not sure how we haven't had any issue posted about this yet.
We're lying to the type saying `headers` is of type `NextApiRequest["headers"]`, but sending in `headers: (key) => headers[key]` to the handler.
This also fixes some workarounds people have had to make with Clerk: https://discord.com/channels/966627436387266600/1102510616326967306/1131989764950724808. Now, `getAuth(req)` **just** works since the `req` is actually a proper `NextApiRequest` like we say it is
(See a test repo here: https://github.com/juliusmarminge/clerk-uploadthing-pages)

fix: don't mess with headers

---

.github/workflows/pr-titles.yaml

Don't need to run on both types:

chore(ci): don't run PR linter on both pr and pr target

---

docs/src/pages/nextjs/appdir.mdx

The file name for a page in the app router is incorrect as it requires the path in the website followed by "/page.tsx" whereas this is missing that:

fix: incorrect app file name

---

docs/src/pages/errors.mdx

fix errors page withInput example to use correct .input syntax

fix(docs): errors page withInput example

---

package.json
packages/solid/package.json
pnpm-lock.yaml

Just me that feels like running dev/build should just run dev in packages/* ?

chore: swap dev and build scripts to favor only packages/*

---

.changeset/polite-lions-peel.md
docs/src/pages/api-reference/react.mdx
examples/appdir/src/app/page.tsx
packages/react/src/components/dropzone.tsx
packages/react/src/components/shared.tsx

Three modes are available:
- manual
- auto
- threshold
`manual` - default behaviour. Upload have to be triggered manually
`auto` - will start upload right after drop
`threshold` - will start upload once if number of dropped files is equal or greater than threshold value. Threshold can be passed either explicitly through config, or maximum number of files will be used. Maximum number of files is equal to largest maximum number among specified types. Though maybe we should use different value
Addresses #273

feat(react): Dropzone modes

---

.changeset/bright-pugs-watch.md
packages/uploadthing/src/sdk/utils.ts

on a bad upload response (within `uploadFilesInternal`), the function calls `UploadThingError.fromResponse()` after having consumed the response body -- leading to a `TypeError` for attempting to consume the response body twice.

fix(sdk): prevent `uploadFilesInternal` from consuming response body twice on bad response

---

.changeset/funny-suns-run.md
packages/uploadthing/src/next-legacy.ts

Closes #362
No idea when this would have been introduced though, as we have ran the body through JSON.parse for a loooong time, so I don't see why it would have broken in this update.

fix(pagedir): only json parse if body is a string

---

.changeset/small-students-sit.md
packages/react/src/components/button.tsx
packages/react/src/components/dropzone.tsx
packages/react/src/components/shared.tsx
packages/solid/src/components/button.tsx
packages/solid/src/components/dropzone.tsx
packages/solid/src/components/shared.tsx
packages/uploadthing/src/internal/component-theming.ts

Fixes two issues:
1. Classes `after:w-[%]` were not generated because they were part of another package not included in tailwind.config. I decided to move progressWidths instead of changing tailwind.config
2. Spinner had been covered by progress bar

fix: progress bar and spinner

---

packages/react/src/useUploadThing.ts
packages/solid/src/useUploadThing.ts
packages/uploadthing/src/client.ts

Pretty straight forward, fires a 0 progress callback the same time we initially set uploading state to true

fix: ensure that uploadProgress fires 0 when upload starts

---

.changeset/slow-coins-begin.md
packages/shared/src/error.ts

Related: https://github.com/pingdotgg/uploadthing/issues/385#issuecomment-1742303132

fix: wrap `response.json()` in a try-catch block

---

.changeset/cold-masks-call.md
packages/shared/src/utils.ts

Hi, when using Remix this file fails because import.meta.env does not exist. Proposing a change to prevent function from failing and use the host value in these cases.
Thanks

fix: Add optional to import.meta.env call

---

.changeset/quick-seahorses-care.md
packages/shared/src/error.ts
packages/uploadthing/src/client.ts

Ref: https://github.com/pingdotgg/uploadthing/issues/385#issuecomment-1747119451
That safeJSONParse couldn't come any sooner 😅

fix: clone res before attempting json parse in `uploadFiles`

---

.changeset/thirty-zebras-know.md
packages/uploadthing/src/sdk/index.ts

`listFiles` now includes the status like shown in the Dashboard. (https://github.com/pingdotgg/uploadthing/issues/429) I added the type for this. As I don't know all possible status options it's a string for now. Maybe make it a union with all possible options?

feat: Upload status type added

---

.changeset/empty-birds-beam.md
.gitignore
docs/src/pages/api-reference/react.mdx
packages/react/src/components/button.tsx
packages/react/src/components/dropzone.tsx
packages/react/src/types.ts
packages/react/src/useUploadThing.ts
packages/solid/src/components/button.tsx
packages/solid/src/components/dropzone.tsx
packages/solid/src/types.ts
packages/solid/src/useUploadThing.ts
packages/uploadthing/src/client.ts

This adds an `onBeforeUploadBegin` callback that is called before `startUpload` to allow for pre-processing of files (ie changing file names etc)

feat: adds a pre-processor callback onBeforeUploadBegin

---

.changeset/neat-buses-flow.md
.changeset/real-peas-compare.md
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/sdk.test.ts
packages/uploadthing/src/server.ts

remove deprecated `utapi` object in favor of initializing with constructor

chore!: remove deprecated `utapi` object in favor of initializing with constructor

---

.changeset/warm-balloons-decide.md
packages/react/package.json

Technically >=13 is required for SSR plugin, but if you don't use that, older versions are allowed.
closes #490

fix: @uploadthing/react peer deps

---

docs/src/pages/api-reference/next.mdx
docs/src/pages/faq.mdx
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/get-full-api-url.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/test/get-full-url.test.ts

un-deprecated `config.callbackUrl` as it could be useful for some edge cases when we can't autodetect the URL.
makes the parsing of both `process.env.UPLOADTHING_URL` and `config.callbackUrl` smarter to handle relative, host and full URL strings.

fix: smarter URL detection

---

.changeset/good-news-travel.md
packages/uploadthing/src/internal/multi-part.ts

fix(upload): URI encode filenames in content-disposition header

---

.changeset/tough-pans-film.md
packages/react/src/useUploadThing.ts
packages/solid/src/useUploadThing.ts

- PR is created to counter the issue faced when trying to validate the uploaded files with async function

feat: allow async onBeforeUploadBegin callback

---

packages/dropzone/src/react.tsx
packages/dropzone/src/solid.tsx

forgot this setting from the port

fix: add style display none to dropzone

---

.changeset/gorgeous-icons-dress.md
examples/minimal-appdir/src/app/api/uploadthing/route.ts
packages/shared/src/error.ts
packages/uploadthing/package.json
packages/uploadthing/src/client.ts
packages/uploadthing/src/express.ts
packages/uploadthing/src/fastify.ts
packages/uploadthing/src/h3.ts
packages/uploadthing/src/internal/dev-hook.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/incompat-node-guard.ts
packages/uploadthing/src/internal/logger.ts
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/utils.ts
packages/uploadthing/src/server.ts
pnpm-lock.yaml

Adds consola logger, adds a config option to enable more verbose logging, e.g.:
```ts
export const { GET, POST } = createNextRouteHandler({
router: uploadRouter,
config: {
logLevel: "debug",
},
});
```

feat: logger for serverside stuff

---

.changeset/bright-weeks-wash.md
packages/uploadthing/src/internal/logger.ts

chore: rm redundant log

---

docs/src/pages/api-reference/server.mdx

Closes #551. Add a sentence on how to use MIME types as keys in the FileRouter and a link to MDN for further reading.

docs(server): Explain use of MIME-types in File Routes

---

.changeset/afraid-terms-live.md
packages/uploadthing/src/express.ts
packages/uploadthing/src/fastify.ts
packages/uploadthing/src/h3.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/src/server.ts

Regression from https://github.com/pingdotgg/uploadthing/pull/514

fix(server-handler): forward original request

---

.changeset/witty-weeks-hear.md
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/sdk.test.ts
packages/uploadthing/src/server.ts

Simplifies when creating File's from Blobs etc wihtout having to use Object.assign() and being warned about readonly shit...

feat: add `UTFile` utility

---

packages/shared/src/types.ts
tooling/eslint-config/base.js

https://www.totaltypescript.com/method-shorthand-syntax-considered-harmful

chore(lint): enable method signature style

---

docs/src/pages/api-reference/react.mdx

The docs didn't mention anything about these missing APIs, and had me scratching my head a bit.
I think I listed them all, might be better to list them in a default-closed accordion or something.

docs: Update `react-dropzone` section

---

.changeset/silent-ravens-raise.md
packages/uploadthing/src/server.ts

missed this entrypoint, currently only exported as a type from the `export type *` but need the runtime symbol too.
Ref #613

fix: export UTFiles from server entrypoint

---

.changeset/eighty-laws-begin.md
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/ut-reporter.ts

technically wouldn't need to be exact match, but why not?

feat: add version lock to ensure `uploadthing/client` and `uploadthing/server`uses same version

---

packages/dropzone/package.json
packages/mime-types/package.json
packages/react/package.json
packages/shared/package.json
packages/solid/package.json
packages/uploadthing/package.json

After doing #603, I've noticed vscode has started suggesting absolute auto-imports such as `import { UPLOADTHING_VERSION } from "uploadthing/constants"` which can cause issues at runtime since that's not an entrypoint in the built package. Adding a lint-rule to force relative imports within each package, so e.g. no file in `@uploadthing/shared` can import using `@uploadthing/shared` paths etc

chore(lint): add `no-restricted-imports`

---

.changeset/popular-apples-walk.md
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/types.ts

failed uploads using PSP were not reported to infra so they would still count towards quota for the user's app even though they didn't occupy space in s3

fix: report failed PSPS uploads as failed to infra

---

.changeset/brave-schools-visit.md
packages/react/src/components/dropzone.tsx

Previously, the button was displayed as disabled when there were no files. This change makes it appear like a normal button, and passes click through to the input. Also removes weird border. 
Before:
After:

fix: Improve dropzone styles to be less confusing

---

docs/src/globals.css

fix: update styles for scalar api code blocks

---

.changeset/eight-cows-fly.md
packages/uploadthing/src/express.ts
packages/uploadthing/src/fastify.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/server.ts

Console might log errors like `An error occured in your middleware function Unauthorized`. A colon should separate the actual error message.
Also changes the incorrect spelling of the work "occurred" everywhere.

fix: Slightly better server error messages

---

docs/src/pages/getting-started/solid.mdx

Related: #697
Also comment out the optional config variable in the docs for solidstart

docs: comment out config by default for solidstart

---

docs/src/pages/getting-started/solid.mdx

This will improve the copy-paste experience of the docs. Checking the header would always fail

docs: Make the uploadRouter in solid the same as in next

---

docs/src/theme.config.js

Fixes https://x.com/t3dotgg/status/1766445250527351012?s=20
Noindex:
While there are ways to auto detect this, i.e off of the Vercel env variable. But given that noindex is more of a destructive action imo it should be manually set. 
In the dev & preview branches, set NEXT_PUBLIC_DISABLE_INDEXING to true in the env vars & validate
Canonical Url:
Uses https://docs.uploadthing.com as the default, adds on the path name. Should also help with deduplication & and forks that don't have the environment variable set.

fix(docs): add noindex option & canonical url

---

docs/src/theme.config.js

Was validating my last PR on the docs site and saw it was set to noindex for some reason
Found that there's a bug where if NEXT_PUBLIC_DISABLE_INDEXING is set to 'true', it will be considered true since it's a string not a boolean. Missed this in my testing since I was just using undefined, sorry about that! 
This also updates og:url from "my-app" to "docs.uploadthing.com" as I noticed that was pointing to the wrong url

fix(docs): noindex fix, the second part

---

.changeset/sharp-emus-tie.md
packages/uploadthing/src/tw.ts

fix(tw plugin): use require.resolve to avoid going outside of fs root

---

docs/src/pages/backend-adapters/express.mdx
docs/src/pages/backend-adapters/fastify.mdx
docs/src/pages/backend-adapters/fetch.mdx
docs/src/pages/backend-adapters/h3.mdx
docs/src/pages/getting-started/appdir.mdx
docs/src/pages/getting-started/astro.mdx
docs/src/pages/getting-started/pagedir.mdx
docs/src/pages/getting-started/solid.mdx

Addresses #712
All examples in docs should now be consistent with the name of the FileRoute, so FE examples work with alternative BE examples. 
Additionally included short note about FileRoutes in all BE docs (was in FE docs only before)

fix(docs): Consistency between examples

---

docs/next.config.mjs
docs/src/theme.config.js

since adding the custom env the docs are no longer auto-deployed from forks since it requires reading environment variables from vercel.
this approach uses a system-env instead so we can remove the env from vercel and thus allowing forks to auto-deploy

docs: allow deployments from forks

---

.github/workflows/ci.yaml
.github/workflows/examples.yaml
.github/workflows/release-canary.yaml
.github/workflows/release.yaml
docs/src/pages/faq.mdx

I think there was a bug in Bun 1.0.31 that caused installs to just forever stall:
Which caused our plan to run out:
This should prevent something similar from happening in the future...

chore(ci): limit jobs runtime

---

docs/src/pages/api-reference/ut-api.mdx

Looking at `uploadthing/packages/uploadthing/src/sdk/types.ts` lines `83-85` I see the following lines of code that do not match the documentation.
```ts
type KeyRename = { key: string; newName: string };
type CustomIdRename = { customId: string; newName: string };
export type RenameFileUpdate = KeyRename | CustomIdRename;
```

docs: Update ut-api.mdx to match type defs

---

.changeset/two-melons-shop.md
packages/mime-types/src/db.ts

Was missing from this allowlist. Does this require additional work?

feat: Add support for 'model/step' MIME type

---

packages/uploadthing/src/internal/multi-part.ts
packages/uploadthing/test/__test-helpers.ts
packages/uploadthing/test/client.test.ts
patches/msw+2.2.10.patch
vitest.config.ts

more tests to improve confidence of Effect rewrite

test: implement polling and retries in test

---

packages/uploadthing/src/internal/dev-hook.ts

makes sure the payload from devhook matches the `opts.file` in `onUploadComplete`

chore: make sure type match in devhook

---

.changeset/heavy-points-hear.md
packages/dropzone/turbo.json

didn't get included on npm build ![CleanShot 2024-04-09 at 23 04 38@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/136c27c7-eaf5-469f-a9c5-38c7bad4941a)

fix: turbo cache not including svelte output

---

.github/workflows/stale-issues.yaml

Automatically marks issues as stale after 2 weeks of inactivity. Closes stale issues after a further 7 days of inactivity. 
Would consider making these shorter as well.

chore: Automatically mark/close stale issues

---

.changeset/famous-forks-attend.md
packages/mime-types/src/index.ts

POC stackblitz: https://stackblitz.com/edit/vitejs-vite-ogve7t?file=build.js
This is a breaking change in the internal package "mime-types", and from what I know it has to be a breaking change. I could not figure out a way to do it without it. In my pr `getExtensions()` and `getTypes()` are exported instead of `extensions` and `types`.
fixes #726

refactor: make @uploadthing/shared tree-shakeable

---

.changeset/kind-years-double.md
.vscode/operators.code-snippets
packages/shared/package.json
packages/shared/src/effect.ts
packages/shared/src/tagged-errors.ts
packages/shared/src/utils.ts
packages/uploadthing/package.json
packages/uploadthing/src/client.ts
packages/uploadthing/src/express.ts
packages/uploadthing/src/fastify.ts
packages/uploadthing/src/h3.ts
packages/uploadthing/src/internal/dev-hook.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/incompat-node-guard.ts
packages/uploadthing/src/internal/logger.ts
packages/uploadthing/src/internal/multi-part.browser.ts
packages/uploadthing/src/internal/multi-part.server.ts
packages/uploadthing/src/internal/presigned-post.server.ts
packages/uploadthing/src/internal/resolve-url.ts
packages/uploadthing/src/internal/to-web-request.ts
packages/uploadthing/src/internal/types.ts
packages/uploadthing/src/internal/ut-reporter.ts
packages/uploadthing/src/internal/validate-request-input.ts
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/utils.ts
packages/uploadthing/src/server.ts
packages/uploadthing/test/__test-helpers.ts
packages/uploadthing/test/request-handler.test.ts
pnpm-lock.yaml

this causes some confusion errors since if the requests failed the schema wont match and it's better to show an error with the response message
updates effect, we can now drop the $-adapter thing to make yielding much nicer 👍🏼

fix: don't validate schema for non-ok requests

---

examples/with-clerk-appdir/package.json
examples/with-clerk-pagesdir/package.json
examples/with-drizzle-appdir/.env.example
examples/with-drizzle-appdir/drizzle.config.ts
examples/with-drizzle-appdir/package.json
examples/with-drizzle-appdir/src/env.mjs
examples/with-drizzle-appdir/src/server/db/index.ts
examples/with-drizzle-appdir/tsconfig.json
examples/with-drizzle-pagesdir/.env.example
examples/with-drizzle-pagesdir/drizzle.config.ts
examples/with-drizzle-pagesdir/package.json
examples/with-drizzle-pagesdir/src/env.mjs
examples/with-drizzle-pagesdir/src/server/db/index.ts
pnpm-lock.yaml

I can't install better-sqlite since node-gyp fails on Python 3.12 (and im too lazy to install 3.11) so swapping to libsql.
Also bumped some other stuff related to the drizzle example while i was at it

chore: update some stuff, use libsql over better-sqlite

---

.changeset/flat-zoos-compete.md
packages/shared/src/effect.ts
packages/shared/src/error.ts
packages/shared/src/tagged-errors.ts
packages/uploadthing/src/client.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/ut-reporter.ts
packages/uploadthing/test/client.test.ts
packages/uploadthing/test/request-handler.test.ts

Closes #777 
- Squashes the FiberFailure to its original cause using `Cause.squash`
- Separates `FetchError` (where a part of the fetch failed) and `BadRequestError` for successful requests with "bad statuscode"

fix: squash fiberfailures, introduce "bad request error"

---

.changeset/fuzzy-toys-smell.md
docs/src/pages/api-reference/react.mdx
packages/react/src/components/dropzone.tsx

Added a prop `onDrop` for the `<UploadDropzone />` component. Whenever the user selects or drops the file it will call the passed `onDrop` callback function.
Closes #805

feat: added onDrop prop for UploadDropzone component

---

.changeset/tame-brooms-end.md
packages/shared/src/effect.ts
packages/shared/src/utils.ts
packages/uploadthing/src/internal/to-web-request.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/test/__test-helpers.ts
tooling/gh-actions/setup/action.yml

Seems like something in Node 20.13 is broken with the spread operator on `Headers`:
Symbols aren't enumerable so they shouldn't show up after a spread, yet they are...
Anyways, this refactor makes it compat with this new behavior, be it intentional or unintentional from their side...

fix: Node 20.13 compat

---

.changeset/twenty-parrots-knock.md
.github/workflows/ci.yaml
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/test/__test-helpers.ts
packages/uploadthing/test/sdk.test.ts

Fixes invalid schema.
Also adds a test suite that runs against a live app (if `UPLOADTHING_TEST_SECRET` is defined) to test a good chunk of the happy paths

fix: invalid schema

---

docs/src/pages/_meta.json
docs/src/pages/working-with-files.mdx

https://docs-uploadthing-git-working-with-files-pinglabs.vercel.app/working-with-files
I think we should have more generic text-based docs (examples and docs that gets straight to the code are great in their way, but I think we should also explain the concepts)
Pages I think could be useful
- `Uploading Files`
- Explain what different ways there are
- Setup an api route on your server using an adapter
- Use `uploadthing/client.genUploader`, client-lib hooks etc
- File never touches your server
- Submit file to your server, then upload from there
- _might be easier to explain once/if we merge prepareUpload and uploadFiles API endpoints and there's only one way to retrieve the presigned URLs_
- Pre-upload operations? Where can you crop, compress images? Optimize files before upload? Verify …

docs: `Working with Files`

---

docs/src/pages/faq.mdx

Vercel has made deployment protection bypass header available on all plan levels as of today. Updated FAQ to reflect this change.

docs: Update faq regarding vercel deployment protection

---

.changeset/wild-terms-know.md
examples/minimal-appdir/src/app/page.tsx
examples/minimal-appdir/src/server/uploadthing.ts
packages/react/src/useUploadThing.ts
packages/solid/src/useUploadThing.ts
packages/svelte/src/lib/create-uploadthing.ts
packages/vue/src/useUploadThing.ts

Closes #859
prefilling the map fixes the average calculation as some items might not be uplaoding from the start

fix: `onUploadProgress` events out of order

---

.changeset/mighty-kiwis-enjoy.md
packages/shared/src/utils.ts
packages/uploadthing/src/internal/dev-hook.ts
packages/uploadthing/src/internal/handler.ts
packages/uploadthing/src/internal/multi-part.server.ts
packages/uploadthing/src/internal/presigned-post.server.ts
packages/uploadthing/src/sdk/index.ts
packages/uploadthing/src/sdk/utils.ts
packages/uploadthing/test/__test-helpers.ts
packages/uploadthing/test/adapters.test.ts
packages/uploadthing/test/client.test.ts
packages/uploadthing/test/request-handler.test.ts
packages/uploadthing/test/sdk.test.ts

go straight to cf dist. instead of being rewritten from vercel first

chore: update api paths

---

docs/src/pages/api-reference/react.mdx

docs: document button config.mode

---

packages/react/package.json
packages/react/src/components/button.tsx
packages/react/src/components/dropzone.tsx
packages/react/src/components/shared.tsx
packages/react/src/types.ts
packages/shared/src/component-utils.ts
packages/solid/package.json
packages/solid/src/components/button.tsx
packages/solid/src/components/dropzone.tsx
packages/solid/src/types.ts
packages/svelte/package.json
packages/svelte/src/lib/component/UploadButton.svelte
packages/svelte/src/lib/component/UploadDropzone.svelte
packages/svelte/src/lib/types.ts
packages/vue/package.json
packages/vue/src/components/button.tsx
packages/vue/src/components/dropzone.tsx
packages/vue/src/types.ts
pnpm-lock.yaml

tailwind-merge is [20kb (7kB gzipped)](https://bundlejs.com/?q=tailwind-merge&treeshake=%5B%7B+twMerge+%7D%5D) that not everyone benefits from. It is only useful for folks applying additional tailwind classes when [theming using TailwindCSS](https://uploadthing-docs-twui.vercel.app/concepts/theming#theming-with-tailwind-css). They can thus provide us the merge function themselves.
This will:
- reduce client bundle by 7kB by default for everyone not using tailwind customizations
- reduce risk of duplicating tailwind-merge in projects already using it, in the case of a version range mismatch
- reduce package dependencies (if that counts as something positive :))
```tsx
import { twMerge } from "tailwind-merge"
<UploadButton 
classList="bg-red-500"
cn={twMerge}
/>
```

chore!: don't bundle tailwind-merge by default

---

packages/shared/package.json
packages/shared/src/crypto.ts
packages/uploadthing/src/internal/handler.ts
pnpm-lock.yaml

Returns a key like `KJNGYKlZPq92Lq0BVqOBeV4QXKqyYlocntI7CxzdHiOfLwFm` instead of a 172ch long base64 string

chore: use sqids instead of sha256 hashing

---

docs/src/mdx/search.js

remove consecutive slashes leading to invalid URLs from search results

fix: docsearch

---

.changeset/wet-llamas-fail.md
docs/src/app/(docs)/uploading-files/page.mdx
packages/shared/src/crypto.ts

Accidentally had `apiKey` instead of `appId` -- this would not work. Also was still using old base64 encoding method, rather than sqids
Also added a note about file seeds

chore: Docs correction - presigned url generation

---

.changeset/spotty-spoons-chew.md
docs/src/app/(docs)/api-reference/client/page.mdx
docs/src/app/(docs)/api-reference/react/page.mdx
examples/minimal-appdir/src/app/page.tsx
packages/react/test/upload-button.test.tsx
packages/uploadthing/src/internal/upload.browser.ts
packages/uploadthing/test/client.test.ts

regresssion from v7 didn't run `onUploadBegin`

fix: run onUploadBegin

---

.changeset/cuddly-pets-jog.md
packages/uploadthing/src/next-legacy.ts
packages/uploadthing/test/adapters.test.ts

`res.json(response.body)` resulted in `{}`.
couldn't find a way to forward the stream as-is, so consuming it and sending it down as JSON as a temporary workaround

fix: nextjs pages adapter response body

---

.changeset/chilled-zoos-exist.md
packages/uploadthing/src/sdk/index.ts

the endpoint is already deprecated long ago and no longer part of the OpenAPI spec: https://docs.uploadthing.com/api-reference/openapi-spec
Docs also says it's deprecated already: https://docs.uploadthing.com/api-reference/ut-api#get-file-urls

chore: deprecate `UTApi.getFileUrls`

---

packages/uploadthing/src/internal/handler.ts

If you're deploying client and server separately it's impossible to upgrade without downtime.
Many versions will still work when they're out of sync, so we can just warn and not cancel the request entirely.

chore: warn instead of error on version mismatch
